# .streamlit/secrets.toml

[connections.sql]
dialect   = "mssql"
driver    = "pyodbc"
host      = "auto.resourceplus.app"
database  = "Data_Lead"
username  = "sa"
password  = "test!serv!123"

# ODBC/SQL Server options
[connections.sql.query]
driver = "ODBC Driver 18 for SQL Server"
encrypt = "yes"
trustservercertificate = "no"
